# Generated by Django 3.0.6 on 2020-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='pair',
            new_name='coinpair',
        ),
    ]
