# Generated by Django 3.0.6 on 2020-05-16 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200514_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
