# Generated by Django 3.0.6 on 2020-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200516_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='apple_user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_apple_user',
            field=models.BooleanField(default=False),
        ),
    ]
