# Generated by Django 3.0.6 on 2020-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200520_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='indicator',
            field=models.CharField(max_length=255),
        ),
    ]
