# Generated by Django 3.0.6 on 2020-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
