# Generated by Django 3.0.6 on 2020-05-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notificationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='trigger_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
